//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDocumentosDataAccess.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Documento
    {
        public int id { get; set; }
        public string idUser { get; set; }
        public string idDocumento { get; set; }
        public string logDescripcion { get; set; }
    }
}
